# Generated by Django 5.2.8 on 2026-02-11 00:00

from django.db import migrations, models


PRICE_LIST_NAMES = [
    "Lista Preço SDE e COE",
    "Lista Preço MT",
    "Lista Preço N e NE",
]


def seed_price_lists(apps, schema_editor):
    PriceList = apps.get_model("sales", "PriceList")
    for name in PRICE_LIST_NAMES:
        PriceList.objects.get_or_create(name=name)


def unseed_price_lists(apps, schema_editor):
    PriceList = apps.get_model("sales", "PriceList")
    PriceList.objects.filter(name__in=PRICE_LIST_NAMES).delete()


def backfill_portal_user_price_lists(apps, schema_editor):
    PortalUser = apps.get_model("sales", "PortalUser")
    PriceList = apps.get_model("sales", "PriceList")
    for user in PortalUser.objects.exclude(price_list__isnull=True).exclude(price_list=""):
        price_list_obj, _ = PriceList.objects.get_or_create(name=user.price_list)
        user.price_lists.add(price_list_obj)


def unbackfill_portal_user_price_lists(apps, schema_editor):
    PortalUser = apps.get_model("sales", "PortalUser")
    for user in PortalUser.objects.all():
        user.price_lists.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "Lista de Preco",
                "verbose_name_plural": "Listas de Preco",
            },
        ),
        migrations.AddField(
            model_name="portaluser",
            name="price_lists",
            field=models.ManyToManyField(blank=True, to="sales.pricelist"),
        ),
        migrations.RunPython(seed_price_lists, unseed_price_lists),
        migrations.RunPython(backfill_portal_user_price_lists, unbackfill_portal_user_price_lists),
    ]
