# Generated by Django 4.2.15 on 2026-02-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_price_lists'),
        ('sales', '0019_produtoinnovaro_modelo_simples'),
    ]

    operations = [
    ]
