# Generated by Django 4.2.16 on 2026-04-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_merge_20260211_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPrecosLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField(verbose_name='Owner ID')),
                ('user_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Usuário')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Acessado em')),
            ],
            options={
                'verbose_name': 'Log de Consulta de Preços',
                'verbose_name_plural': 'Logs de Consulta de Preços',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['owner_id'], name='sales_consu_owner_i_16a662_idx'), models.Index(fields=['accessed_at'], name='sales_consu_accesse_114d4c_idx')],
            },
        ),
    ]
