# Generated by Django 5.2.8 on 2026-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_portaluser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número com DDI e DDD, ex: 5511999999999', max_length=20),
        ),
    ]
