# Generated by Django 5.2.8 on 2026-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_portaluser_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone com DDD, ex: (85) 99999-9999', max_length=20),
        ),
    ]
